### ISSUE TITLE
vsearch error 

### ISSUE THREAD

**Issue by kholt1992** [vmaffei/dada2_to_picrust#13]
Hi, 

This should be a simple fix. When I try running the following in R:
system('vsearch --usearch_global 16s_13_5_precalculated.tab --db 97_otus.fasta --matched 16s_13_5_precalculated.tab --id 0.97')

I get the error: 
sh: vsearch: command not found

But when I try biocLite("vsearch") I get the following:

BioC_mirror: https://bioconductor.org
Using Bioconductor 3.6 (BiocInstaller 1.28.0), R 3.4.2 (2017-09-28).
Installing package(s) ‘vsearch’
Warning message:
package ‘vsearch’ is not available (for R version 3.4.2)

**Comment by vmaffei** [comment]
Hi kholt, vsearch is a separate program that can be downloaded from here: https://github.com/torognes/vsearch 

Scroll to the bottom for installation options. Once you've built (or downloaded) a copy of the vsearch binary, swap out `system('vsearch --usearch...` for the full path to the binary: `system('/path/to/vsearch' --usearch...`

Let me know if you run into any issues!

**Comment by kholt1992** [comment]
Thanks! When I run the following after giving full path to binary this is what I get:

> system('/Users/kevinholt/Downloads/vsearch-2.6.2-macos-x86_64/bin/vsearch --usearch_global gg_13_5_study_db.fasta.pre --db 97_otus.fasta --matched gg_13_5_study_db.fasta --id 0.97')
vsearch v2.6.2_macos_x86_64, 8.0GB RAM, 4 cores
https://github.com/torognes/vsearch

Reading file 97_otus.fasta 100%
WARNING: 2 invalid characters stripped from FASTA file: _(2)
36360648 nt in 55404 seqs, min 140, max 2995, avg 656
Masking 100%
Counting k-mers 100%
Creating k-mer index 100%
Searching 100%
Matching query sequences: 1 of 1172 (0.09%)

Why would I have only one matching query sequence? Thanks for the help, I am new to this.

**Comment by kholt1992** [comment]
If I reduce threshold from 97% to 90% I still only get 6 matching sequences

**Comment by vmaffei** [comment]
Hey kholt, no problem at all! Do you know what sequences you're working with by chance? Post a small sample if you'd like me to take a quick look. Run the code below and copy/paste the output into here.

```sh
# print first 15 lines of fasta file
head -n 15 gg_13_5_study_db.fasta.pre
```

**Comment by vmaffei** [comment]
Actually, try matching query reads in both forward and reverse orientation before posting your seqs:
```r
system('/Users/kevinholt/Downloads/vsearch-2.6.2-macos-x86_64/bin/vsearch --usearch_global gg_13_5_study_db.fasta.pre --db 97_otus.fasta --matched gg_13_5_study_db.fasta --id 0.97 --strand both')
```

**Comment by kholt1992** [comment]
I am using V4V5 16s amplicon sequences (518F 926R). Here is a table showing lengths of merged reads:

> table(nchar(getSequences(seqtab)))

226 227 229 231 242 250 254 258 275 283 284 286 290 295 306 310 311 312 313 314 316 317 318 321 323 324 325 327 329 
  1   1   1   1   1   1   1   1   2   2   1   1   1   1   1   1   1   2   2   2   1   1   1   1   1   2   1   1   1 
331 340 341 345 349 353 354 359 363 364 365 366 367 368 369 370 371 372 373 374 375 376 382 390 394 397 399 
  1   1   1   1   1   3   1   1   1   1   3   8   5   5  92 189  42  82 402 279  11   1   1   1   2   1   1 

After trying to match query reads in F+R,  here are first 15 lines of fasta file:

> head(gg_13_5_study_db.fasta, 15)
                                                                                 V1
1                                                                          >study_1
2  CGGAGGATCCGAGCGTTATCCGGATTTATTGGGTTTAAAGGGAGCGTAGATGGATGTTTAAGTCAGTTGTGAAAGTTTGC
3  GGCTCAACCGTAAAATTGCAGTTGATACTGGATATCTTGAGTGCAGTTGAGGCAGGCGGAATTCGTGGTGTAGCGGTGAA
4  ATGCTTAGATATCACGAAGAACTCCGATTGCGAAGGCAGCCTGCTAAGCTGCAACTGACATTGAGGCTCGAAAGTGTGGG
5  TATCAAACAGGATTAGATACCCTGGTAGTCCACACGGTAAACGATGAATACTCGCTGTTTGCGATATACGGCAAGCGGCC
6                                AAGCGAAAGCGTTAAGTATTCCACCTGGGGAGTACGCCGGCAACGGTGAA
7                                                                          >study_2
8  CGGAGGATGCGAGCGTTATCCGGATTTATTGGGTTTAAAGGGTGCGCAGGCGGTCTGTTAAGTCAGCGGTCAAAGCCCGG
9  GGCTCAACCCCGGCCCGCCGTTGAAACTGGCAGTCTCGAGTTGGAGAGAAGTATGCGGAATGCGCGGTGTAGCGGTGAAA
10 TGCATAGATATCGCGCAGAACTCCGATTGCGAAGGCAGCATGCCGGCTCCACACTGACGCTGAGGCACGAAAGCGTGGGT
11 ATCGAACAGGATTAGATACCCTGGTAGTCCACGCAGTAAACGATGAATGCTGGCTGTCCGGGGGGATTGACCCCTGGGTG
12                            GCGAAGCGAAAGCGATAAGCATTCCACCTGGGGAGTACGCCGGCAACGGTGAA
13                                                                         >study_3
14 CGGAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGCACGCAGGCGGTCTGTCAAGTCGGATGTGAAATCCCCG
15 GGCTCAACCTGGGAACTGCATTCGAAACTGGCAGGCTTGAGTCTTGTAGAGGGGGGTAGAATTCCAGGTGTAGCGGTGAA

**Comment by kholt1992** [comment]
Given:

writeFasta(fasta, file = "gg_13_5_study_db.fasta.pre")

I just quickly imported back into Rstudio to view first 15 lines, the .pre suffix was removed automatically, maybe because there was already a .pre file in my environment with the 1 matching query sequence.

**Comment by vmaffei** [comment]
Gotcha! So just to check...did matching F+R match the majority of seqs (or at least more seqs) to 97_otus.fasta?

**Comment by kholt1992** [comment]
it matches the same sequences. 

> system('/Users/kevinholt/Downloads/vsearch-2.6.2-macos-x86_64/bin/vsearch --usearch_global gg_13_5_study_db.fasta.pre --db 97_otus.fasta --matched gg_13_5_study_db.fasta --id 0.97 --strand both')
vsearch v2.6.2_macos_x86_64, 8.0GB RAM, 4 cores
https://github.com/torognes/vsearch

Reading file 97_otus.fasta 100%
WARNING: 2 invalid characters stripped from FASTA file: _(2)
36360648 nt in 55404 seqs, min 140, max 2995, avg 656
Masking 100%
Counting k-mers 100%
Creating k-mer index 100%
Searching 100%
Matching query sequences: 1 of 1172 (0.09%)

**Comment by vmaffei** [comment]
I ran vsearch on your `>study_1` and `>study_2` seqs above and both matched to 97_otus.fasta

```txt
142290491 nt in 99322 seqs, min 1254, max 2353, avg 1433
Masking 100%
Counting unique k-mers 100%
Creating index of unique k-mers 100%
Searching 100%
Matching query sequences: 2 of 2 (100.00%)
```

The first thing that jumps out is that our 97_otus.fastas have different summary statistics (99322 seqs vs. 55404 seqs, etc). I didn't see `WARNING: 2 invalid characters stripped from FASTA file: _(2)`. Consider re-downloading the reference fasta and give it another try?

Visit http://greengenes.secondgenome.com/downloads/database/13_5 and download `gg_13_5_otus.tar.gz (310867 KiB)`

**Comment by kholt1992** [comment]
I re-downloaded 97_fasta and got a Fatal error message this time. So I also tried the other reference fasta. Here's how it worked out for both: 

> system('/Users/kevinholt/Downloads/vsearch-2.6.2-macos-x86_64/bin/vsearch --usearch_global gg_13_5_study_db.fasta.pre --db 97_otus.fasta --matched gg_13_5_study_db.fasta --id 0.97')
vsearch v2.6.2_macos_x86_64, 8.0GB RAM, 4 cores
https://github.com/torognes/vsearch

Reading file 97_otus.fasta

Fatal error: illegal character '-' on line 2 in FASTA file
> # filter sequences that diverge from gg_13_5 by 97%
> # depending on how well greengenes covers your study sequences, consider reducing 97% to 70 or 50%
> system('/Users/kevinholt/Downloads/vsearch-2.6.2-macos-x86_64/bin/vsearch --usearch_global gg_13_5_study_db.fasta.pre --db gg_13_5.fasta --matched gg_13_5_study_db.fasta --id 0.97')
vsearch v2.6.2_macos_x86_64, 8.0GB RAM, 4 cores
https://github.com/torognes/vsearch

Reading file gg_13_5.fasta 100%
1769520677 nt in 1262986 seqs, min 1111, max 2368, avg 1401
Masking 100%
Counting k-mers 100%
Creating k-mer index 100%
Searching 100%
Matching query sequences: 466 of 1172 (39.76%)
>

**Comment by vmaffei** [comment]
Getting closer! For the `97_otus.fasta`, make sure you use the copy located in `rep_set` not `rep_set_aligned`.

**Comment by kholt1992** [comment]
Thanks, that seemed to work. However, I am currently stuck on the following command in part 3:

format_tree_and_trait_table.py -t ./genome_prediction/study_tree.tree -i gg_ko_counts.tab -o ./genome_prediction/format/KEGG/
Usage: format_tree_and_trait_table.py [options] {-t/--input_tree INPUT_TREE -i/--input_trait_table INPUT_TRAIT_TABLE}


When I try to run this the process says "Killed" after about 15 minutes. Here are the last few lines of code before it got killed: 

199545 internal_node_199545 True
199546 334427 True
199547 289636 True
199548 3408597 True
Killed

I was using 15 cores and 10gb of memory (per node)

**Comment by vmaffei** [comment]
Great!

The "Killed" error may be due to low memory. Are 10 gb of memory specifically dedicated to each core, or were you just dividing total RAM by number of cores? You'll need ~80 gb of spare memory to complete this and the remaining pipeline steps since they are data heavy. The scripts in Part 3-4 are not parallelized anyways, so only 1 core will be used. Let me know if your setup has any memory restrictions that you know of. If that's not an issue, I'm happy to help troubleshoot further!

**Comment by kholt1992** [comment]
I think the 10gb of memory was dedicated to each core. I tried using 80gb of memory this time on one core but when I try to run the following command in a batch script I am getting the error below. Do you know what this means?

#!/bin/bash
#SBATCH -n 1
#SBATCH -t 4:00:00
#SBATCH --mem=80G
module load picrust/1.1.0

ancestral_state_reconstruction.py -i ./format/KEGG/trait_table.tab -t ./format/KEGG/pruned_tree.newick -o ./asr/KEGG_asr_counts.tab -c ./asr/asr_ci_KEGG.tab

## SLURM PROLOG ###############################################################
##    Job ID : 18550550
##  Job Name : picrust.sh
##  Nodelist : node850
##      CPUs : 1
##  Mem/Node : 81920 MB
## Directory : /gpfs/data/svaishna/kholt/PiCrust
##   Started : Wed Jan 10 15:26:09 EST 2018
###############################################################################
module: loading 'picrust/1.1.0'
sh: line 1: 14528 Killed                  R -f /gpfs/runtime/opt/picrust/1.1.0/lib/python2.7/site-packages/PICRUSt-1.1.0-py2.7.egg/picrust/support_files/R/ace.R --args "./format/KEGG/pruned_tree.newick" "./format/KEGG/trait_table.tab" pic /tmp/tmpLtzuEUGvUVvwA3pruDGg.txt /tmp/tmpikL0Zm4UoPGyd0xy0ZDR.txt > "/tmp/tmpMFhLLRELLoD7CYrw0gOu.txt" 2> "/tmp/tmpmGLSOWQ7na7gnS1nkraR.txt"
Traceback (most recent call last):
  File "/gpfs/runtime/opt/picrust/1.1.0/bin/ancestral_state_reconstruction.py", line 4, in <module>
    __import__('pkg_resources').run_script('PICRUSt==1.1.0', 'ancestral_state_reconstruction.py')
  File "/gpfs/runtime/opt/python/2.7.3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/gpfs/runtime/opt/python/2.7.3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1524, in run_script
    exec(code, namespace, namespace)
  File "/gpfs/runtime/opt/picrust/1.1.0/lib/python2.7/site-packages/PICRUSt-1.1.0-py2.7.egg/EGG-INFO/scripts/ancestral_state_reconstruction.py", line 91, in <module>
    main()
  File "/gpfs/runtime/opt/picrust/1.1.0/lib/python2.7/site-packages/PICRUSt-1.1.0-py2.7.egg/EGG-INFO/scripts/ancestral_state_reconstruction.py", line 74, in main
    asr_table,ci_table = ace_for_picrust(opts.input_tree_fp,opts.input_trait_table_fp,'pic',HALT_EXEC=opts.debug)
  File "/gpfs/runtime/opt/picrust/1.1.0/lib/python2.7/site-packages/PICRUSt-1.1.0-py2.7.egg/picrust/ace.py", line 97, in ace_for_picrust
    asr_prob_table=LoadTable(filename=tmp_output_prob_path,header=True,sep='\t')
  File "/gpfs/runtime/opt/python/2.7.3/lib/python2.7/site-packages/cogent/__init__.py", line 170, in LoadTable
    delimiter = sep, limit=limit, **kwargs)
  File "/gpfs/runtime/opt/python/2.7.3/lib/python2.7/site-packages/cogent/parse/table.py", line 138, in load_delimited
    f = file(filename, "U")
IOError: [Errno 2] No such file or directory: '/tmp/tmpikL0Zm4UoPGyd0xy0ZDR.txt'

**Comment by kholt1992** [comment]
If I run the same command just on the command line after using interact to get enough memory, I also get the same error: 

[kholt1@node853 PiCrust]$ ancestral_state_reconstruction.py -i ./format/KEGG/trait_table.tab -t ./format/KEGG/pruned_tree.newick -o ./asr/KEGG_asr_counts.tab -c ./asr/asr_ci_KEGG.tab
+





sh: line 1: 27360 Killed                  R -f /gpfs/runtime/opt/picrust/1.1.0/lib/python2.7/site-packages/PICRUSt-1.1.0-py2.7.egg/picrust/support_files/R/ace.R --args "./format/KEGG/pruned_tree.newick" "./format/KEGG/trait_table.tab" pic /tmp/tmpx3mcltOD2EMVBRv0xdeO.txt /tmp/tmpYmRqdvhRktcW97aO0PL5.txt > "/tmp/tmpgNQvmmBYF66EnbnfPdEZ.txt" 2> "/tmp/tmp7ApfW0pXe7h1zBAGtu6p.txt"
Traceback (most recent call last):
  File "/gpfs/runtime/opt/picrust/1.1.0/bin/ancestral_state_reconstruction.py", line 4, in <module>
    __import__('pkg_resources').run_script('PICRUSt==1.1.0', 'ancestral_state_reconstruction.py')
  File "/gpfs/runtime/opt/python/2.7.3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/gpfs/runtime/opt/python/2.7.3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1524, in run_script
    exec(code, namespace, namespace)
  File "/gpfs/runtime/opt/picrust/1.1.0/lib/python2.7/site-packages/PICRUSt-1.1.0-py2.7.egg/EGG-INFO/scripts/ancestral_state_reconstruction.py", line 91, in <module>
    main()
  File "/gpfs/runtime/opt/picrust/1.1.0/lib/python2.7/site-packages/PICRUSt-1.1.0-py2.7.egg/EGG-INFO/scripts/ancestral_state_reconstruction.py", line 74, in main
    asr_table,ci_table = ace_for_picrust(opts.input_tree_fp,opts.input_trait_table_fp,'pic',HALT_EXEC=opts.debug)
  File "/gpfs/runtime/opt/picrust/1.1.0/lib/python2.7/site-packages/PICRUSt-1.1.0-py2.7.egg/picrust/ace.py", line 97, in ace_for_picrust
    asr_prob_table=LoadTable(filename=tmp_output_prob_path,header=True,sep='\t')
  File "/gpfs/runtime/opt/python/2.7.3/lib/python2.7/site-packages/cogent/__init__.py", line 170, in LoadTable
    delimiter = sep, limit=limit, **kwargs)
  File "/gpfs/runtime/opt/python/2.7.3/lib/python2.7/site-packages/cogent/parse/table.py", line 138, in load_delimited
    f = file(filename, "U")
IOError: [Errno 2] No such file or directory: '/tmp/tmpYmRqdvhRktcW97aO0PL5.txt'
[kholt1@node853 PiCrust]$ +
bash: +: command not found

**Comment by vmaffei** [comment]
Interesting! The error ```IOError: [Errno 2] No such file or directory: '/tmp/tmpYmRqdvhRktcW97aO0PL5.txt'``` seems to be related to accessing temporary data inside ```/tmp```. You may want to show this to whoever maintains your system at your institution, who may be able to troubleshoot or tweak configuration settings to get you past this error. Unfortunately, I'm not quite sure how to tackle this!

Consider re-running this step without the -c option (since this error occurs within a script that's accessing the confidence interval data):

```sh
ancestral_state_reconstruction.py -i ./format/KEGG/trait_table.tab -t ./format/KEGG/pruned_tree.newick -o ./asr/KEGG_asr_counts.tab
```

**Comment by kholt1992** [comment]
When I removed the -c option I get this: 

## SLURM PROLOG ###############################################################
##    Job ID : 18574276
##  Job Name : ancestralstate.sh
##  Nodelist : node851
##      CPUs : 1
##  Mem/Node : 81920 MB
## Directory : /gpfs/data/svaishna/kholt/PiCrust
##   Started : Fri Jan 12 14:36:12 EST 2018
###############################################################################
module: loading 'picrust/1.1.0'
Traceback (most recent call last):
  File "/gpfs/runtime/opt/picrust/1.1.0/bin/ancestral_state_reconstruction.py", line 4, in <module>
    __import__('pkg_resources').run_script('PICRUSt==1.1.0', 'ancestral_state_reconstruction.py')
  File "/gpfs/runtime/opt/python/2.7.3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/gpfs/runtime/opt/python/2.7.3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1524, in run_script
    exec(code, namespace, namespace)
  File "/gpfs/runtime/opt/picrust/1.1.0/lib/python2.7/site-packages/PICRUSt-1.1.0-py2.7.egg/EGG-INFO/scripts/ancestral_state_reconstruction.py", line 91, in <module>
    main()
  File "/gpfs/runtime/opt/picrust/1.1.0/lib/python2.7/site-packages/PICRUSt-1.1.0-py2.7.egg/EGG-INFO/scripts/ancestral_state_reconstruction.py", line 74, in main
    asr_table,ci_table = ace_for_picrust(opts.input_tree_fp,opts.input_trait_table_fp,'pic',HALT_EXEC=opts.debug)
  File "/gpfs/runtime/opt/picrust/1.1.0/lib/python2.7/site-packages/PICRUSt-1.1.0-py2.7.egg/picrust/ace.py", line 95, in ace_for_picrust
    " %s" % "\n".join(result["StdErr"].readlines()))
RuntimeError: R reported an error on stderr: sh: R: command not found


I'm not sure if the Runtime error is b/c R is not in my environment or what, but I'll contact the people who manage the university computing cluster

**Comment by kholt1992** [comment]
The issue was indeed a memory error. I can get everything in your workflow to work. However, when I try to use the metagenomes_contributions.py command, which I do not think is in your workflow, I get the following error:

[kholt1@login002 PiCrust]$ metagenome_contributions.py -i norm_counts.biom -l K00001 -o ko_metagenome_contributions
Traceback (most recent call last):
  File "/gpfs/runtime/opt/picrust/1.1.0/bin/metagenome_contributions.py", line 4, in <module>
    __import__('pkg_resources').run_script('PICRUSt==1.1.0', 'metagenome_contributions.py')
  File "/gpfs/runtime/opt/python/2.7.3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/gpfs/runtime/opt/python/2.7.3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1524, in run_script
    exec(code, namespace, namespace)
  File "/gpfs/runtime/opt/picrust/1.1.0/lib/python2.7/site-packages/PICRUSt-1.1.0-py2.7.egg/EGG-INFO/scripts/metagenome_contributions.py", line 135, in <module>
    main()
  File "/gpfs/runtime/opt/picrust/1.1.0/lib/python2.7/site-packages/PICRUSt-1.1.0-py2.7.egg/EGG-INFO/scripts/metagenome_contributions.py", line 117, in main
    genome_table = convert_precalc_to_biom(genome_table_fh,ids_to_load)
  File "/gpfs/runtime/opt/picrust/1.1.0/lib/python2.7/site-packages/PICRUSt-1.1.0-py2.7.egg/picrust/util.py", line 98, in convert_precalc_to_biom
    raise ValueError,"No OTUs match identifiers in precalculated file. PICRUSt requires an OTU table reference/closed picked against GreenGenes.\nExample of the first 5 OTU ids from your table: {0}".format(', '.join(list(ids_to_load)[:5]))
ValueError: No OTUs match identifiers in precalculated file. PICRUSt requires an OTU table reference/closed picked against GreenGenes.
Example of the first 5 OTU ids from your table: study_738, study_633, study_735, study_736, study_328

**Comment by vmaffei** [comment]
Glad you got everything working in the workflow! Rerun the metagenomes_contributions.py with the ```-c``` option pointing to your custom ko_precalculated.tab file:

```metagenome_contributions.py -i norm_counts.biom -l K00001 -o ko_metagenome_contributions -c ./genome_prediction/predict_traits/ko_precalculated.tab ```

Let me know if that doesn't work for you, and I'll investigate further!

**Comment by kholt1992** [comment]
it worked! thanks so much. by the way, how do you install the STAMP program for picrust analysis? My computing cluster is giving me permission issues i cannot get around, and installing it on my mac seems to be tricky. Thanks again

**Comment by vmaffei** [comment]
No problem! Glad it worked. What issues are you running into on your mac with STAMP? Any specific errors? Are you using these installation instructions: http://kiwi.cs.dal.ca/Software/Quick_installation_instructions_for_STAMP

**Comment by vmaffei** [comment]
Just installed it successfully on my mac using the following:
```sh
# run these one at a time
# create env
conda create -n STAMP python=2.7
# activate env
source activate STAMP
# install STAMP dependencies
conda install numpy scipy matplotlib
# install STAMP
pip install STAMP
# open STAMP
STAMP
```
Make sure to install python 2.7...3.3/3.6 didn't work for me.

**Comment by kholt1992** [comment]
I've been having issues downloading PyQt4

For example: 

Kevins-MacBook-Pro:~ kevinholt$ conda install pyqt=4.11.4
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - anaconda-navigator -> pyqt[version='>=5.6'] -> qt=5.6
  - pyqt=4.11.4 -> qt[version='>=4.8.6,<5.0'] -> freetype=2.5
Use "conda info <package>" to see the dependencies for each package.

So when I try final line of code you provided I get the following:


(STAMP) Kevins-MacBook-Pro:~ kevinholt$ STAMP
Traceback (most recent call last):
  File "/Users/kevinholt/anaconda2/envs/STAMP/bin/STAMP", line 32, in <module>
    from stamp import STAMP
  File "/Users/kevinholt/anaconda2/envs/STAMP/lib/python2.7/site-packages/stamp/STAMP.py", line 38, in <module>
    from stamp.GUI.plotDlg import PlotDlg  # forward reference so py2app recognizes this file is required
  File "/Users/kevinholt/anaconda2/envs/STAMP/lib/python2.7/site-packages/stamp/GUI/plotDlg.py", line 24, in <module>
    from PyQt4 import QtGui, QtCore
ImportError: No module named PyQt4

**Comment by vmaffei** [comment]
Forgot that PyQt requires installation of Qt! : http://splinter.readthedocs.io/en/latest/drivers/installing_pyqt.html 

Take a look at this and install Qt. Install SIP through conda afterwards if you can!
