### ISSUE TITLE
predict_traits.py memory issue?

### ISSUE THREAD

**Issue by giriarteS** [vmaffei/dada2_to_picrust#7]
I got the following message when running predict_traits.py:
predict_traits.py -i ./genome_prediction/format/16S/trait_table.tab -t ./genome_prediction/format/16S/reference_tree.newick -r ./genome_prediction/asr/16S_asr_counts.tab -o ./genome_prediction/predict_traits/16S_precalculated.tab -a -c ./genome_prediction/asr/asr_ci_16S.tab -g "$(< study_ids)"
Killed: 9

The -g option is only useful for lists of < 10 organism id, my list has 3500, can I use -l instead with the sample_counts.biom file?

**Comment by vmaffei** [comment]
Hey giriarteS, I run into the same issue when the number of sequences is pretty large (>2000 or so). The "-l" option works pretty well (just tried it). Let me know if it works for you, too:

```sh
# convert biom to tsv using biom-format
biom convert -i sample_counts.biom -o sample_counts.tab --to-tsv
# predict traits using -l in place of -g
predict_traits.py -i ./genome_prediction/format/16S/trait_table.tab \
   -t ./genome_prediction/format/16S/reference_tree.newick \
   -r ./genome_prediction/asr/16S_asr_counts.tab \
   -o ./genome_prediction/predict_traits/16S_precalculated.tab \
   -a -c ./genome_prediction/asr/asr_ci_16S.tab \
   -l sample_counts.tab
```

**Comment by giriarteS** [comment]
It didn't work for me, I am getting the same message: 
Killed: 9

**Comment by vmaffei** [comment]
Out of curiosity, what tipped you off that this might be a memory issue? Did you notice free RAM or storage space dropping while running the script? 

Also which Greengenes database version are you using? 13.5 97% clustered, unclustered, etc?

Troubleshooting ideas:
1) Do you get the same message if you run `predict_traits.py` on a single OTU:
```sh
predict_traits.py -i ./genome_prediction/format/16S/trait_table.tab \
   -t ./genome_prediction/format/16S/reference_tree.newick \
   -r ./genome_prediction/asr/16S_asr_counts.tab \
   -o ./genome_prediction/predict_traits/16S_precalculated.tab \
   -a -c ./genome_prediction/asr/asr_ci_16S.tab \
   -g 1111883
```

**Comment by junhuili** [comment]
It didn't work for me either. I am using 13.5, 97% clustered (filter sequences that diverge from gg_13_5 by 90%), around 290 study OTUs. Same message while using a single OTU.

```
Traceback (most recent call last):
  File "/home/junhui/miniconda2/bin/predict_traits.py", line 451, in <module>
    main()
  File "/home/junhui/miniconda2/bin/predict_traits.py", line 280, in main
    trait_label = trait_label, verbose=opts.verbose)
  File "/home/junhui/miniconda2/lib/python2.7/site-packages/picrust/predict_traits.py", line 735, in calc_nearest_sequenced_taxon_index
    tree.tipToTipDistances(annot_plus_to_predict)
  File "/home/junhui/miniconda2/lib/python2.7/site-packages/cogent/core/tree.py", line 2033, in tipToTipDistances
    result = zeros((num_tips, num_tips), float) # tip by tip matrix
MemoryError
```

**Comment by vmaffei** [comment]
Hi @junhuili out of curiosity how much RAM is installed on your machine? It'd be nice to know whether the MemoryError is due to insufficient memory or some other error. For troubleshooting, try repeating with a smaller Greengenes database (ex: 85_otus.fasta) to see if that triggers the error.

**Comment by junhuili** [comment]
32 GB RAM

**Comment by junhuili** [comment]
I run in HPC with 100000 MB memory, but I got similar message 'MemoryError'. Any thoughts?

Traceback (most recent call last):
  File "/packages/python/anaconda/latest/bin/predict_traits.py", line 451, in <module>
    main()
  File "/packages/python/anaconda/latest/bin/predict_traits.py", line 280, in main
    trait_label = trait_label, verbose=opts.verbose)
  File "/packages/python/anaconda/latest/lib/python2.7/site-packages/picrust/predict_traits.py", line 735, in calc_nearest_sequenced_taxon_index
    tree.tipToTipDistances(annot_plus_to_predict)
  File "/packages/python/anaconda/latest/lib/python2.7/site-packages/cogent/core/tree.py", line 2065, in tipToTipDistances
    return result+result.T, tip_order
MemoryError

**Comment by vmaffei** [comment]
I ran a few full trials with the 97% Greengenes db, increasing the maximum available RAM each time. I got a `MemoryError` whenever max RAM was <  85Gb. For >= 85Gb, no errors occurred. 

For 32Gb, I was able to run the pipeline fully using the 94% Greengenes db, but not the 97% db (due to the same `MemoryError`.

Try `grep ">" gg_13_5_study_db.fasta | wc -l` to count how many sequences are in your study fasta. Let me know what comes out. Just want to make sure we know how many sequences are going into the pipeline at Part 1. The study fastas I made using the 94% and 97% databases contained ~50,000 and ~100,000 sequences, respectively, for a ~290 OTU study. The error (I believe) is trigged due to the size of the newick tree thats produced from these sequences, which goes into the genome prediction steps. 

If you can get access to the HPC again, could you post the output to `ulimit -a`? Just want to check whether any memory caps were in place in the background that could have caused the error. 

Happy to help write up a solution once we find out what's causing the error!

**Comment by junhuili** [comment]
Totally, 99322 sequences in the study fasta.

**Comment by vmaffei** [comment]
Thanks @junhuili I'm working on a solution to make this step more memory efficient...will post it once it's ready!

**Comment by vmaffei** [comment]
@junhuili @giriarteS 

Give this a try when you have a chance. This is a quick-and-dirty fix that should get you going. Replace both predict_traits.py steps with the following:

```sh
# replace both predict_traits.py steps with the following
predict_traits.py -i ./genome_prediction/format/16S/trait_table.tab \
 -t ./genome_prediction/format/16S/reference_tree.newick \
 -r ./genome_prediction/asr/16S_asr_counts.tab \
 -o ./genome_prediction/predict_traits/16S_precalculated.tab \
 -l ./genome_prediction/sample_counts.tsv
# create tmp directories
mkdir ./genome_prediction/traits_tmp
mkdir ./genome_prediction/predict_traits/tmp/
# run predict_traits X KEGG genes at a time and output to individual files
BATCH=2000
for ((i=2, j=$BATCH; j<=$(head -n 1 ./genome_prediction/format/KEGG/trait_table.tab | wc -w); i=i+$BATCH, j=j+$BATCH));
do
	echo "$i - $j IDs"
	cat ./genome_prediction/format/KEGG/trait_table.tab | cut -f 1,$i-$j > ./genome_prediction/traits_tmp/trait_tmp_$i.txt ; 
	cat ./genome_prediction/asr/KEGG_asr_counts.tab | cut -f 1,$i-$j > ./genome_prediction/traits_tmp/asr_tmp_$i.txt ; 
	predict_traits.py -i ./genome_prediction/traits_tmp/trait_tmp_$i.txt \
		 -t ./genome_prediction/format/KEGG/reference_tree.newick \
		 -r ./genome_prediction/traits_tmp/asr_tmp_$i.txt \
		 -o ./genome_prediction/predict_traits/tmp/ko_precalculated.$i.tab \
		 -l ./genome_prediction/sample_counts.tsv; 
done;
# combine results into single ko_precalculated.tab file
cut -f 1 ./genome_prediction/predict_traits/tmp/ko_precalculated.2.tab > ./genome_prediction/predict_traits/ko_precalculated.tab
ls ./genome_prediction/predict_traits/tmp/ | grep "ko_precalculated" | while read f; 
do 
	paste ./genome_prediction/predict_traits/ko_precalculated.tab <(cut -f 2- ./genome_prediction/predict_traits/tmp/$f) > ./genome_prediction/predict_traits/results_tmp; 
	cp ./genome_prediction/predict_traits/results_tmp ./genome_prediction/predict_traits/ko_precalculated.tab;  
done; 
# proceed with Part 4 as usual
```

The error is caused in predict_traits.py when the script loads too much data to RAM. This occurs during confidence interval generation (optional -a parameter) and when predict_traits.py attempts to load two databases: ```KEGG_asr_counts.tab``` and ```trait_table.tab```  to RAM for processing. These modified steps drop the -a flag and process the KEGG gene data in specified, manageable batches. For RAM ~ 32Gb, a batch size of 2000 worked well for me. Feel free to alter this as needed.

Let me know if you run into any errors. Happy to help you both with this further if needed.
